
---
# FALTA EDITAR IPS!

HOSTNAME: COR-CP01
TYPE: CP
CONTEXT: SRP
ASN_LOCAL:
ASN_REMOTE:
IP_L0_BL1:
IP_L0_BL2:
SRP_BL1_IP_P2P:
SRP_BL2_IP_P2P:
SRP_VLAN_1:
SRP_VLAN_2:
SRP_L0_BGP:
SRP_L0_ICSR:
SRP_3_10:
  IP:
  MASK:
SRP_3_11:
  IP:
  MASK:
SRP_4_10:
  IP:
  MASK:
SRP_4_11:
  IP:
  MASK:
SRP_5_10:
  IP:
  MASK:
SRP_5_11:
  IP:
  MASK:
SRP_6_10:
  IP:
  MASK:
SRP_6_11:
  IP:
  MASK:
SRP_7_10:
  IP:
  MASK:
SRP_7_11:
  IP:
  MASK:
SRP_8_10:
  IP:
  MASK:
SRP_8_11:
  IP:
  MASK: