
---
# FALTA EDITAR IPS!

HOSTNAME: OLL-CP01
TYPE: CP
CONTEXT: DRA
ASN_LOCAL:
ASN_REMOTE:
IP_L0_BL1:
IP_L0_BL2:
DRA_BL1_IP_P2P:
DRA_BL2_IP_P2P:
DRA_VLAN_1:
DRA_VLAN_2:
DRA_L0_BGP:
DRA_L0_GX:
DRA_L0_GY:
DRA_3_10:
  IP:
  MASK:
DRA_3_11:
  IP:
  MASK:
DRA_4_10:
  IP:
  MASK:
DRA_4_11:
  IP:
  MASK:
DRA_5_10:
  IP:
  MASK:
DRA_5_11:
  IP:
  MASK:
DRA_6_10:
  IP:
  MASK:
DRA_6_11:
  IP:
  MASK:
DRA_7_10:
  IP:
  MASK:
DRA_7_11:
  IP:
  MASK:
DRA_8_10:
  IP:
  MASK:
DRA_8_11:
  IP:
  MASK: