
---
#OLLEROS CP

HOSTNAME: OLL-CP01
TYPE: CP
CONTEXT: SAEGW
ASN_LOCAL:
ASN_REMOTE:
IP_L0_BL1:
IP_L0_BL2:
SAEGW_BL1_IP_P2P:
SAEGW_BL2_IP_P2P:
SAEGW_VLAN_1:
SAEGW_VLAN_2:
SAEGW_L0_BGP:
SAEGW_L0_S11_AR:
SAEGW_L0_S11_PY:
SAEGW_L0_S11_UY:
SAEGW_L0_S5_SGW_AR:
SAEGW_L0_S5_SGW_PY:
SAEGW_L0_S5_SGW_UY:
SAEGW_L0_S5_PGW_AR:
SAEGW_L0_S5_PGW_PY:
SAEGW_L0_S5_PGW_UY:
SAEGW_L0_SX_C:
SAEGW_L0_SX_U:
SAEGW_3_10:
  IP:
  MASK:
SAEGW_3_11:
  IP:
  MASK:
SAEGW_4_10:
  IP:
  MASK:
SAEGW_4_11:
  IP:
  MASK:
SAEGW_5_10:
  IP:
  MASK:
SAEGW_5_11:
  IP:
  MASK:
SAEGW_6_10:
  IP:
  MASK:
SAEGW_6_11:
  IP:
  MASK:
SAEGW_7_10:
  IP:
  MASK:
SAEGW_7_11:
  IP:
  MASK:
SAEGW_8_10:
  IP:
  MASK:
SAEGW_8_11:
  IP:
  MASK: