services:
  ansible:
    container_name: ansible
    tty: true
    image: custom_ansible:1.0
    build: 
      context: ./
      dockerfile: ./AnsibleDockerfile
    working_dir: /binded
    volumes:
      - C:\Users\jlugosal\OneDrive - Cisco\Scripts\Ansible\ansible_microservice:/binded