services:
  ansible:
    container_name: ansible
    tty: true
    build: .
    working_dir: /binded
    volumes:
      - C:\Users\jlugosal\OneDrive - Cisco\Scripts\Docker\ansible_microservice:/binded