
---
#CORDOBA CP - FALTA EDITAR IPS!

HOSTNAME: COR-CP01
TYPE: UP
CONTEXT: SRP
ASN_LOCAL:
ASN_REMOTE:
IP_L0_BL1:
IP_L0_BL2:
SRP_BL1_IP_P2P:
SRP_BL2_IP_P2P:
SRP_VLAN_1:
SRP_VLAN_2:
SRP_L0_BGP:
SRP_L0_ICSR:
SRP_1_10:
  IP:
  MASK:
SRP_1_11:
  IP:
  MASK: