
---
#CORDOBA CP - FALTA EDITAR IPS!

HOSTNAME: COR-CP01
TYPE: UP
CONTEXT: SGI_MPLS
ASN_LOCAL:
ASN_REMOTE:
IP_L0_VPE:
SGI_MPLS_VPE_IP_P2P_1:
SGI_MPLS_VPE_IP_P2P_2:
SGI_MPLS_VLAN_1:
SGI_MPLS_VLAN_2:
SGI_MPLS_L0_BGP:
SGI_MPLS_1_10:
  IP:
  MASK:
SGI_MPLS_1_11:
  IP:
  MASK: