
---
#CORDOBA CP - FALTA EDITAR IPS!

HOSTNAME: COR-CP01
TYPE: UP
CONTEXT: SGi
ASN_LOCAL:
ASN_REMOTE:
IP_L0_VPE:
SGI_VPE_IP_P2P_1:
SGI_VPE_IP_P2P_2:
SGI_VLAN_1:
SGI_VLAN_2:
SGI_L0_BGP:
SGI_1_10:
  IP:
  MASK:
SGI_1_11:
  IP:
  MASK: