
---
#CORDOBA CP - FALTA EDITAR IPS!

HOSTNAME: COR-CP01
TYPE: UP
CONTEXT: SAEGW
ASN_LOCAL:
ASN_REMOTE:
IP_L0_BL1:
IP_L0_BL2:
SAEGW_BL1_IP_P2P:
SAEGW_BL2_IP_P2P:
SAEGW_VLAN_1:
SAEGW_VLAN_2:
SAEGW_L0_BGP:
SAEGW_L0_S11_AR:
SAEGW_L0_S11_PY:
SAEGW_L0_S11_UY:
SAEGW_L0_S1U_AR:
SAEGW_L0_S1U_PY:
SAEGW_L0_S1U_UY:
SAEGW_L0_S5_SGW_AR:
SAEGW_L0_S5_SGW_PY:
SAEGW_L0_S5_SGW_UY:
SAEGW_L0_S5_PGW_AR:
SAEGW_L0_S5_PGW_PY:
SAEGW_L0_S5_PGW_UY:
SAEGW_L0_SX_C:
SAEGW_L0_SX_U:
SAEGW_1_10:
  IP:
  MASK:
SAEGW_1_11:
  IP:
  MASK: