
---
#CORDOBA CP - FALTA EDITAR IPS!

HOSTNAME: COR-CP01
TYPE: UP
CONTEXT: SGi_IPSec
ASN_LOCAL:
ASN_REMOTE:
IP_L0_VPE:
SGI_IPSEC_VPE_IP_P2P_1:
SGI_IPSEC_VPE_IP_P2P_2:
SGI_IPSEC_VLAN_1:
SGI_IPSEC_VLAN_2:
SGI_IPSEC_L0_BGP:
SGI_IPSEC_1_10:
  IP:
  MASK:
SGI_IPSEC_1_11:
  IP:
  MASK: